todoproject/todoapp/urls.py
from django.urls import path
from . import views
app_name='todoapp'

urlpatterns =[
    path('',views.add,name='add'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("todoapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

class Task(models.Model):

    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name
# Create your models here.

todoproject/todoapp/forms.py
from django import forms

from .models import Task


class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject/todoapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import TodoForm
from .models import Task


def add(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority = request.POST.get('priority', '')
        date=request.POST.get('date','')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task1':task1})
def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None,instance=task)
    if f.is_valid():
        f.save()
        return  redirect('/')
    return render(request,'edit.html',{'f':f,'task':task})

# def details(request):
#
#     return render(request,'details.html',)

# Create your views here.

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">-->
<!--    <link rel="stylesheet" href="{% static 'style.css' %}">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'style.css' %}">
<!--    <link type="text/css" rel="stylesheet" href="{% static 'style.css' %}">-->
<!--    <link rel=”stylesheet” type=”text/css” href=”../static/style.css">-->
<!--   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
</head>
<body>
{% block content%}
{% endblock %}


</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form  method="POST">
    {% csrf_token %}
    <p> Are you sure to delete the task?</p>
    <button type="submit">confirm</button>
</form>
{% endblock %}

todoproject/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for i in task %}
{{i.name}}
{{i.priority}}
{% endfor %}

</body>
</html>

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{f.as_p}}
  <button type="submit">confirm</button>
</form>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="com-md-12">
            <div class="Banner">
                <div class="Banner_text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
            {% csrf_token %}
            <div class="form-group">
                 <input type="text"  class="form-control" name="task" placeholder="Taskname">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="priority" placeholder="priority">
            </div>
                <div class="form-group">
                <input type="date" class="form-control" name="date" placeholder="Enter your Date">
            </div>
            <input type="submit" class="btn btn-success">
            </form>
        </div>
        <div class="col-md-6">
            <h4> Task to be Completed</h4>
            {% for i in task1 %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-Title">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-danger" href="{% url 'todoapp:update' i.id %}">Update</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>

    </div>
</div>

{% endblock %}